ALTER DATABASE Snap_State MODIFY FILE (name='Snap_State' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\Snap_State.mdf');
ALTER DATABASE Snap_Monitor MODIFY FILE (name='Snap_Monitor_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\Snap_Monitor.mdf');
ALTER DATABASE EnterpriseVaultDirectory MODIFY FILE (name='VaultDev70' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EnterpriseVaultDirectory.mdf');
ALTER DATABASE DAmondrian MODIFY FILE (name='DAmondrian_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian.MDF');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_10' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_13.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_46' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_14.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_57' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_15.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_69' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_16.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_18' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_17.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_75' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_18.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_76' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_19.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_77' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_20.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_80' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_21.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_81' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_22.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_84' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_23.ndf');
ALTER DATABASE DAmondrian MODIFY FILE (name='ftrow_DataFullTextIndex_DAmondrian_88' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DAmondrian_24.ndf');
ALTER DATABASE EVJournalVaultStore MODIFY FILE (name='JournalVaultStore70' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EVJournalVaultStore.mdf');
ALTER DATABASE EnterpriseVaultMonitoring MODIFY FILE (name='EnterpriseVaultMonitoring_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EnterpriseVaultMonitoring.mdf');
ALTER DATABASE EVAccelerator MODIFY FILE (name='EVAccelerator_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EVAccelerator.mdf');
ALTER DATABASE EVAccelerator2 MODIFY FILE (name='EVAccelerator2_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EVAccelerator2.mdf');
ALTER DATABASE EVCAConfiguration MODIFY FILE (name='EVCAConfiguration_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EVCAConfiguration.mdf');
ALTER DATABASE EVMailboxVaultStore MODIFY FILE (name='MailboxVaultStore70' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVMailboxVaultStore.mdf');
ALTER DATABASE EVVSFileSystemVaultStore_3 MODIFY FILE (name='EVVSFileSystemVaultStore_370' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\EVVSFileSystemVaultStore_3.mdf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_170' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1.mdf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_000' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_1.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_001' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_2.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_002' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_3.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_003' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_4.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_004' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_5.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_005' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_6.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_006' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_7.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_007' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_8.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_008' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_9.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_009' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_10.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_010' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_11.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_011' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_12.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_012' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_13.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_013' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_14.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_014' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_15.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_015' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_16.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_016' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_17.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_017' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_18.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_018' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_19.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_019' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_20.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_020' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_21.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_021' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_22.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_022' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_23.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_023' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_24.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_024' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_25.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_025' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_26.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_026' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_27.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_027' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_28.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_028' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_29.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_029' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_30.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_030' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_31.ndf');
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 MODIFY FILE (name='EVVSGDefaultUpgradeGroup_1_1_data_031' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EVVSGDefaultUpgradeGroup_1_1_32.ndf');
ALTER DATABASE DACustodianManager MODIFY FILE (name='DACustodianManager_Data' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\DACustodianManager.mdf');

ALTER DATABASE Snap_State SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE Snap_Monitor SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EnterpriseVaultDirectory SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE DAmondrian SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVJournalVaultStore SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EnterpriseVaultMonitoring SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVAccelerator SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVAccelerator2 SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVCAConfiguration SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVMailboxVaultStore SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVVSFileSystemVaultStore_3 SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE EVVSGDefaultUpgradeGroup_1_1 SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE DACustodianManager SET OFFLINE WITH ROLLBACK IMMEDIATE;

