ALTER DATABASE  [INSERT DATABASE NAME] MODIFY FILE (name=' [INSERT DATABASE LOGICAL FILENAME]' , filename='S:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\[INSERT DATABASE FILENAME].mdf');

ALTER DATABASE  [INSERT DATABASE NAME] SET OFFLINE WITH ROLLBACK IMMEDIATE;

